Repository Swipe-Jeju/swiping-jeju-frontend_v2, pull requests merged in 2024-04, with the labels that each got.

#21 ✨Feat: API 연동작업
  package-lock.json
  package.json
  src/app/(home)/page.tsx
  src/app/api/description/route.ts
  src/app/api/title/route.ts
  src/app/page.tsx
  src/app/result/[id]/page.tsx
  src/app/result/page.tsx
  src/app/swiping/data/index.ts
  src/app/swiping/page.tsx
  src/components/home/HomeKeywordInput.tsx
  src/components/home/HomeLanding.tsx
  src/components/result/KakaoMap.tsx
  src/components/result/ResultHotplaceList.tsx
  src/components/swiper/BackCard.tsx
  src/components/swiper/Card.tsx
  src/components/swiper/FrontCard.tsx
  src/components/swiper/kakaoMap.tsx
  src/constants/result/placeDummy.ts
  src/context/store.tsx
  src/hooks/result/useResultData.ts
  src/hooks/swipe/useSwipe.ts
  src/interfaces/result/result.ts
  src/interfaces/swipe/index.ts
Labels: api 📬, feature ✨, size/L, 🙋‍♂️ 희찬

#24 Axios 연동 기본 세팅과 metatdata 추가
  public/favicon.ico
  public/images/og_image.png
  scripts/ingest-data-local.ts
  src/app/api/keywords/route.ts
  src/app/api/title/route.ts
  src/app/favicon.ico
  src/app/layout.tsx
  src/app/result/[id]/page.tsx
  src/app/swiping/data/index.ts
  src/app/swiping/page.tsx
  src/components/home/HomeKeywordInput.tsx
  src/components/home/HomeLanding.tsx
  src/components/result/KakaoShareButton.tsx
  src/components/swiper/BackCard.tsx
  src/components/swiper/Card.tsx
  src/components/swiper/FrontCard.tsx
  src/components/swiper/kakaoMap.tsx
  src/context/store.tsx
  src/hooks/result/useResultData.ts
  src/hooks/useFetch.ts
  src/hooks/useMutate.ts
  src/interfaces/home/home.ts
  src/interfaces/swipe/index.ts
  src/lib/instance.ts
  src/utils/langchain/getSplittedDocs.ts
  src/utils/langchain/localRetriever.ts
  src/utils/log.ts
Labels: api 📬, refactor 🔨, setting ⚙️, size/XL, 🙋‍♂️ 정민

#25 🚀Deploy: 1.0 배포
  public/favicon.ico
  public/images/og_image.png
  scripts/ingest-data-local.ts
  src/app/api/keywords/route.ts
  src/app/api/title/route.ts
  src/app/favicon.ico
  src/app/layout.tsx
  src/app/result/[id]/page.tsx
  src/app/swiping/data/index.ts
  src/app/swiping/page.tsx
  src/components/home/HomeKeywordInput.tsx
  src/components/home/HomeLanding.tsx
  src/components/result/KakaoShareButton.tsx
  src/components/swiper/BackCard.tsx
  src/components/swiper/Card.tsx
  src/components/swiper/FrontCard.tsx
  src/components/swiper/kakaoMap.tsx
  src/context/store.tsx
  src/hooks/result/useResultData.ts
  src/hooks/useFetch.ts
  src/hooks/useMutate.ts
  src/interfaces/home/home.ts
  src/interfaces/swipe/index.ts
  src/lib/instance.ts
  src/utils/langchain/getSplittedDocs.ts
  src/utils/langchain/localRetriever.ts
  src/utils/log.ts
Labels: deploy 🚀

#28 🎨 Desig : Home
  src/app/(home)/page.tsx
  src/components/common/NextButton.tsx
  src/components/home/HomeKeywordInput.tsx
  src/components/home/HomeLanding.tsx
  src/components/home/HomeMapSelection.tsx
  src/components/home/HomeProgressbar.tsx
  src/components/home/HomeTitle.tsx
  src/interfaces/home/home.ts
  src/lib/instance.ts
  src/utils/home/mapUtils.ts
Labels: feature ✨, PR status : done ✔️, refactor 🔨, size/L, 🙋‍♂️ 희찬

#29 🚀 Deploy: Landing Page Update -v.1.0.4
  src/app/(home)/page.tsx
  src/components/common/NextButton.tsx
  src/components/home/HomeKeywordInput.tsx
  src/components/home/HomeLanding.tsx
  src/components/home/HomeMapSelection.tsx
  src/components/home/HomeProgressbar.tsx
  src/components/home/HomeTitle.tsx
  src/interfaces/home/home.ts
  src/lib/instance.ts
  src/utils/home/mapUtils.ts
Labels: deploy 🚀

#30 Main -> Dev Merge PR
  src/components/home/HomeKeywordInput.tsx
Labels: bugfix 🐞, 🙋‍♂️ 정민
