Repository Swipe-Jeju/swiping-jeju-frontend_v2, pull requests merged in 2024-03, with the labels that each got.

#1 Nextjs 초기 세팅
  .eslintrc.json
  .github/pull_request_template.md
  .gitignore
  .husky/pre-commit
  .husky/prepare-commit-msg
  .prettierignore
  .prettierrc.json
  README.md
  next.config.mjs
  package-lock.json
  package.json
  public/favicon.ico
  public/images/ReadMeLogo.png
  public/next.svg
  public/vercel.svg
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/api/hello.ts
  src/pages/index.tsx
  src/styles/BreakPoints.ts
  src/styles/Global.ts
  src/styles/Theme.ts
  src/styles/fonts.module.css
  src/styles/styled.d.ts
  tsconfig.json
Labels: enhancement, good first issue

#2 ✨ Feat: GitAction File, Folder Structure
  .github/ISSUE_TEMPLATE/issue_template.md
  .github/workflows/pr_size_labeler.yml
  src/(route)/home/.keep
  src/(route)/result/.keep
  src/(route)/swiping/.keep
  src/components/.keep
Labels: documentation

#4 Initial Nextjs app router setting with tailwind
  .eslintrc.json
  next.config.mjs
  package-lock.json
  package.json
  postcss.config.js
  public/images/not-found.png
  src/(route)/home/.keep
  src/(route)/result/.keep
  src/(route)/swiping/.keep
  src/app/favicon.ico
  src/app/home/page.tsx
  src/app/layout.tsx
  src/app/not-found.tsx
  src/app/page.tsx
  src/app/result/page.tsx
  src/app/swiping/page.tsx
  src/components/.keep
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/api/hello.ts
  src/pages/index.tsx
  src/styles/BreakPoints.ts
  src/styles/Global.ts
  src/styles/Theme.ts
  src/styles/fonts.module.css
  src/styles/globals.css
  src/styles/reset.css
  src/styles/styled.d.ts
  tailwind.config.ts
  tsconfig.json
Labels: setting ⚙️, size/XL

#5 ✨ Feat: Home - 2Step(Landing, Map)
  public/images/background/char_3.png
  public/images/background/char_green.png
  public/images/background/char_orange.png
  public/images/background/logo.png
  public/images/background/nocap.png
  public/images/jeju_map.png
  public/images/loading.gif
  public/images/map/map_0.png
  public/images/map/map_4.png
  public/images/map/map_4_5.png
  public/images/map/map_4_5_6.png
  public/images/map/map_4_5_6_7.png
  public/images/map/map_4_5_7.png
  public/images/map/map_4_6.png
  public/images/map/map_4_6_7.png
  public/images/map/map_4_7.png
  public/images/map/map_5.png
  public/images/map/map_5_6.png
  public/images/map/map_5_6_7.png
  public/images/map/map_5_7.png
  public/images/map/map_6.png
  public/images/map/map_6_7.png
  public/images/map/map_7.png
  public/images/nav_logo.png
  public/images/share/facebook.png
  public/images/share/google.png
  public/images/share/kakao.png
  public/images/share/naver.png
  public/svg/close.svg
  public/svg/dislike.svg
  public/svg/fork_right.svg
  public/svg/like.svg
  public/svg/locationIcon.svg
  public/svg/pause.svg
  public/svg/swipe_complete.svg
  public/svg/undo.svg
  public/svg/undo_white.svg
  src/app/home/page.tsx
  src/app/layout.tsx
  src/components/home/HomeLanding.tsx
  src/components/home/HomeMapSelection.tsx
  src/constants/home/home.ts
  src/hooks/home/useDelayedClick.ts
  src/hooks/home/useMapSelection.ts
  src/interfaces/home/home.ts
  src/utils/home/mapUtils.ts
  src/utils/home/updateSwipingAlbumAndProceed.ts
  tailwind.config.ts
Labels: feature ✨, PR status : done ✔️, refactor 🔨, size/XL, 🙋‍♂️ 희찬

#8 ✨Feature : Home Page 제작
  package-lock.json
  package.json
  src/app/home/page.tsx
  src/app/not-found.tsx
  src/components/common/NextButton.tsx
  src/components/home/HomeKeywordInput.tsx
  src/components/home/HomeMapSelection.tsx
  src/components/home/HomeTitle.tsx
  src/components/loading/Loading.jsx
  src/constants/home/keyword.ts
  src/constants/home/map.ts
  src/hooks/home/useKeywords.ts
  src/interfaces/home/home.ts
  src/utils/home/getRandomKeyword.ts
  src/utils/home/mapUtils.ts
Labels: feature ✨, PR status : done ✔️, refactor 🔨, size/L, 🙋‍♂️ 희찬

#11 Feature/swipe page
  .eslintrc.json
  next.config.mjs
  package-lock.json
  package.json
  public/images/0.jpeg
  public/images/1.jpeg
  public/images/2.jpeg
  public/images/3.jpeg
  src/app/swiping/layout.tsx
  src/app/swiping/page.tsx
  src/components/swiper/BackCard.tsx
  src/components/swiper/Card.tsx
  src/components/swiper/FrontCard.tsx
  src/components/swiper/SwipeButton.tsx
  src/components/swiper/kakaoMap.tsx
  src/hooks/swipe/useSwipe.ts
  src/interfaces/swipe/index.ts
  src/utils/swipe/openKakaoMap.ts
  svgr.d.ts
  tsconfig.json
Labels: feature ✨, refactor 🔨, setting ⚙️, size/XL, 🙋‍♂️ 정민

#17 Update README.md
  README.md
Labels: size/XS

#15 Feature/extract keyword nl
  .gitignore
  data/keywords.txt
  next.config.mjs
  package-lock.json
  package.json
  scripts/ingest-data-local.ts
  src/app/api/description/route.ts
  src/app/api/keywords/route.ts
  src/app/api/title/route.ts
  src/app/swiping/data/index.ts
  src/app/swiping/page.tsx
  src/components/home/HomeKeywordInput.tsx
  src/prompt/index.ts
  src/utils/langchain/combineDocument.ts
  src/utils/langchain/getSplittedDocs.ts
  src/utils/langchain/localRetriever.ts
Labels: feature ✨, size/XL, 🙋‍♂️ 정민
